### ISSUE TITLE
Support individual metrics per route

### ISSUE THREAD

**Issue by cosminci** [RustedBones/akka-http-metrics#12]
Given the fact the `.recordMetrics` API returns a `Flow`, rather than a `Route`, it's not possible to instantiate separate collectors per API - it can only be done on the parent route.

This can be an important requirement when supporting multiple APIs in a single web server (e.g. ingesting streaming content and serving static resources).

Supporting individual metrics per route could either be done automatically (e.g. for Prometheus add a label with an inferred route name / path), or manually, by using instantiating the `akka-http-metrics` flow per `Route`.

**Comment by bilal-fazlani** [comment]
+1 

I have another use case.

As of today, Akka Http only allows using HTTP2 with `bindAndHandleAsync` method. Since `.recordMetrics` returns a flow, I can't use this library with HTTP2.

**Comment by RustedBones** [comment]
Thanks a lot for the improvements suggestions :100: !
This is what I can say about them:

1. API returns a Flow, rather than a Route

This was a design decision ensure that all request served by the server are counted.

It would be possible to expose a `Route` along with `Flow` for advanced usage. However, user should keep in mind that the route would have to be [`sealed`](https://doc.akka.io/docs/akka-http/current/routing-dsl/routes.html) by the library to force handling of the rejections & exception.

2. Supporting individual metrics per route could either be done automatically

`automatically` is problematic. We can't put the path in the label as it can violate the metrics [best practices](https://prometheus.io/docs/practices/naming/#labels). Let's consider a path containing a segment: `GET /users/:id/email`. The number of paths is unbounded, exposing this as a label violates the guideline.

To expose the path as a metrics label, a mechanism to replace segments by constant must implemented.

3. Akka Http only allows using HTTP2 with `bindAndHandleAsync`

This statement is wrong. If you check the implementation of [`bindAndHandleAsync`](https://github.com/akka/akka-http/blob/601c238cd85e5cfe1771e1ef0365ee1bad659a7c/akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala#L314), you see that it is a simple conversion from the async function to the flow used in `bindAndHandle`

```scala
if (http2Enabled)
        log.debug("The akka.http.server.preview.enable-http2 flag was set, " +
          "but a plain HttpConnectionContext (not Https) was given, binding using plain HTTP...")

      val definitiveParallelism =
        if (parallelism > 0) parallelism
        else if (parallelism < 0) throw new IllegalArgumentException("Only positive values allowed for `parallelism`.")
        else settings.pipeliningLimit
      bindAndHandle(Flow[HttpRequest].mapAsync(definitiveParallelism)(handler), interface, port, connectionContext, settings, log)
    }
```

I would rather go for solution 2 to expose metrics per route, Let's see now if this is possible :sweat_smile:

**Comment by cosminci** [comment]
The path label doesn't need to be populated with the actual value for the path segment, though generating it probably requires some code instrumentation (maybe some annotations).

**Comment by bilal-fazlani** [comment]
@RustedBones 

I will stare my understanding. Please correct me if I am wrong.

This is the full method:

```scala
  def bindAndHandleAsync(
    handler:   HttpRequest ⇒ Future[HttpResponse],
    interface: String, port: Int = DefaultPortForProtocol,
    connectionContext: ConnectionContext = defaultServerHttpContext,
    settings:          ServerSettings    = ServerSettings(system),
    parallelism:       Int               = 0,
    log:               LoggingAdapter    = system.log)(implicit fm: Materializer): Future[ServerBinding] = {
    val http2Enabled = settings.previewServerSettings.enableHttp2 && connectionContext.http2 != Never
    val http2Forced = connectionContext.http2 == Always
    if (http2Enabled && (connectionContext.isSecure || http2Forced)) {
      // We do not support HTTP/2 negotiation for insecure connections (h2c), https://github.com/akka/akka-http/issues/1966
      log.debug("Binding server using HTTP/2{}", if (http2Forced) " (forced to be used without TLS)" else "")

      val definitiveSettings =
        if (parallelism > 0) settings.mapHttp2Settings(_.withMaxConcurrentStreams(parallelism))
        else if (parallelism < 0) throw new IllegalArgumentException("Only positive values allowed for `parallelism`.")
        else settings
      Http2Shadow.bindAndHandleAsync(handler, interface, port, connectionContext, definitiveSettings, definitiveSettings.http2Settings.maxConcurrentStreams, log)(fm)
    } else {
      if (http2Enabled)
        log.debug("The akka.http.server.preview.enable-http2 flag was set, " +
          "but a plain HttpConnectionContext (not Https) was given, binding using plain HTTP...")

      val definitiveParallelism =
        if (parallelism > 0) parallelism
        else if (parallelism < 0) throw new IllegalArgumentException("Only positive values allowed for `parallelism`.")
        else settings.pipeliningLimit
      bindAndHandle(Flow[HttpRequest].mapAsync(definitiveParallelism)(handler), interface, port, connectionContext, settings, log)
    }
  }
```

it looks like `if (http2Enabled)` block does not bind to HTTP2 but `if (http2Enabled && (connectionContext.isSecure || http2Forced))` does.  Using `Http2Shadow.bindAndHandleAsync` which is private to akka.

```scala
      if (http2Enabled)
        log.debug("The akka.http.server.preview.enable-http2 flag was set, " +
          "but a plain HttpConnectionContext (not Https) was given, binding using plain HTTP...")
```

the above block just prints a warning that saying - [ you wanted http2 but you are not getting it ]. 
and then it continues to bind with HTTP 1.

With this understanding, is there a possibility to use HTTP2 and also use `.recordMetrics` ?

**Comment by RustedBones** [comment]
@bilal-fazlani Ouch sorry. I was really wrong.
http2 is supported by reflection and an implementation is in the `akka-http2-support` module.
I'm opening a separate ticket for it,

**Comment by bilal-fazlani** [comment]
Thanks 👍
