### ISSUE TITLE
Extension methods from HttpMetrics break Http().newServerAt

### ISSUE THREAD

**Issue by dafeiw** [RustedBones/akka-http-metrics#139]
Hi, if I have this import: `import fr.davit.akka.http.metrics.core.HttpMetrics._` in the file, the `Http().newServerAt` will no long work. 
the version I used is 1.5. Is it as expected?

**Comment by RustedBones** [comment]
Hi @dafeiw
Can you share the compile error / exception you are getting ?

**Comment by dafeiw** [comment]
Hi @RustedBones ,
Sorry I should have made it clearer. It doesn't have compiler error or exception. 
When akka http server boots up, a GET command to the endpoint created by `Http().newServerAt` returns `There was an internal server error`. The terminal output doesn't have error/exception. If I remove the `import` statement, it works fine.
the version of akka http is 10.2.2.

**Comment by RustedBones** [comment]
Ok. I'll try to reproduce. I'll keep you posted.

**Comment by RustedBones** [comment]
Hi @dafeiw . I indeed managed to reproduce the bug on version `1.5.0`.
In that version, the `import fr.davit.akka.http.metrics.core.HttpMetrics._` takes precedence for route to function / flow conversion over default akka.
When not used with the metered server, this causes issue because requests are expected to have a trace metadata, which was not added.

You can force akka conversion in the case to keep the import.
```scala
.bind(Route.toFunction(route))
```
 or 
```scala
.bindFlow(Route.toFlow(route))
```

Also, starting with version `1.6.0`, this implicit conversions have been removed in favor of an internal route conversion in the bind methods.

Check the best option for you and tell me if this solved your problem :)

**Comment by dafeiw** [comment]
Thanks @RustedBones !  The workaround works for me.
