### ISSUE TITLE
Add a method bindFlow(handler: Flow[I,O,Mat]) to HttpMetricsServerBuilder

### ISSUE THREAD

**Issue by vineet1987** [RustedBones/akka-http-metrics#184]
When I plug the akka-http-metrics library version 1.6.0 there is no provision to pass a flow in the bindFlow method. The case class HttpMetricsServerBuilder only has the below method for bindFlow:<br>
`def bindFlow(route: Route): Future[ServerBinding]`

The previous version 1.5.1 had the support for handlerFlow: Flow[HttpRequest, HttpResponse, _].

We use the library **rocks.heikoseeberger.accessus.Accessus** where we use the method ".withTimeStampedAccessLog(....) whcih return Flow[HttpRequest, HttpResponse, M]: <br>

`Http.newSeverAt(host,port).bindFlow(routes.withTimeStampedAccessLog(.....)`

After using the akka-http-metrics library which we need to track latency for akka http routes the below code is no longer compiling due to constraints on the last line:

`
import rocks.heikoseeberger.accessus.Accessus._
import fr.davit.akka.http.metrics.core.HttpMetrics._

val server = Http()
      .newMeteredServerAt(settings.server.host, settings.server.port, MetricsController.registry)
    
server.bindFlow(route.withTimestampedAccessLog(...)).  //This line is not compiling as the bindFlow method expects a route
`

**Comment by RustedBones** [comment]
Hi @vineet1987 .

I agree the API is not intuitive. The reason `bindFlow` is taking a `Route` as argument instead of a `Flow` is due to the path labelling. Indeed, to support the feature, the library needs to know if the response has been handled or not. This can only be done when transforming a `Route` to a `Flow` (called Route sealing operation).

Since `Accessus` support is deprecated and `akka-http` is moving towards a function API (especially for HTTP2), I would suggest to do the following:

```scala
val routes = ???
val flow = routes.withTimeStampedAccessLog(.....)
val meteredFlow = HttpMetrics.meterFlow(metricsHandler).join(flow)
Http.newSeverAt(host,port).bindFlow(meteredFlow)
```

This should do the job. Can you give a try and let me know ?

**Comment by vineet1987** [comment]
Hello @RustedBones, Thanks a lot. I was able to integrate the above solution and it works fine !!
