### ISSUE TITLE
Adding http method as dimension

### ISSUE THREAD

**Issue by wake42** [RustedBones/akka-http-metrics#40]
Would it be possible to add the http method as a dimension to the path. Currently I've made separate "pathLabeled" specifying if its a GET, POST etc. But it would be better to be able to have each path endpoint combined, no matter what the http method is.

**Comment by RustedBones** [comment]
Hi @wake42.
That's a great suggestion. Just in time for v1.0.0. I'm adding this to the milestone

**Comment by wake42** [comment]
Hi,
Thanks for this, it works really well, but we have a problem. OPTIONS is also a method, but that one is not handled with path (pathLabeled) in Akka so right now all OPTIONS register with full path including any id:s (OPTIONS /user/1 becomes a different metric from /user/2). I tried to add a path for OPTIONS but it seems that our cors handling is responding before we get to the routes.
Do you have any good idea of how to handle this.
We would be fine with dropping all OPTIONS calls from the metrics.

**Comment by RustedBones** [comment]
Thanks for coming back on this issue. I suppose you are using [akka-http-cors](https://github.com/lomigmegard/akka-http-cors). The issue comes form [this line](https://github.com/lomigmegard/akka-http-cors/blob/99177afbd8d940dfcd35ba839e1f391e97b0b739/akka-http-cors/src/main/scala/ch/megard/akka/http/cors/scaladsl/CorsDirectives.scala#L72).

Basically, when developing `akka-http-metrics` I made the wrong assumption that success responses are created when path is fully matched. This is not the case.

There are 2 possible solutions:
  - Have a custom RequestContext that can tell on complete how much of the path was matched
  - Have the path labelled as opt-in

In both cases this is not related to the http method. I'm closing this issue and will reference it in a new dedicated one.
