### ISSUE TITLE
Specify label for pathSingleSlash route

### ISSUE THREAD

**Issue by Fraer** [RustedBones/akka-http-metrics#69]
Hello, with `akka-http-metrics-prometheus` v1.2.0 
when i use `pathSingleSlash` directive to match all incoming requests to the root or / for example:
```
pathSingleSlash {
   get {
        complete("welcome !")
    }
} ~  path("version") {
   get {
        complete("1.0.0")
   }
}
```
so when i hit the root 
`curl -X GET http://localhost:8080`

The associated counter to this root endpoint is specified with an unlabelled path:
```
# TYPE akka_http_responses_total counter
akka_http_responses_total{method="GET",path="unlabelled",status="2xx",} 1.0
```

Is there a way to specify a label for the root path ?

**Comment by RustedBones** [comment]
Hi @Fraer,

Sorry for the late answer. As stated in the [doc](https://github.com/RustedBones/akka-http-metrics#path), you need to opt-in to get the dimension.

In your case, if you want to label on the root only, you can do
`pathLabeled(PathEnd)` or  `pathPrefixLabeled(PathEnd)` instead of `pathSingleSlash`.

Calling `curl -X GET http://localhost:8080` will get `path="/"`
and `curl -X GET http://localhost:8080/version` will get `path="unlabelled"` because the label is only applied on the inner route.

Hope this helps.

**Comment by Fraer** [comment]
Yes it works, i get the correct label `/`  thanks a lot!
