### ISSUE TITLE
JVM metrics?

### ISSUE THREAD

**Issue by rparree** [RustedBones/akka-http-metrics#72]
Hi,

I was wondering if there was a way to include JVM metrics such as heap size, garbage collections etc

tx.,

**Comment by RustedBones** [comment]
Hi @rparree 

Exposing the JVM metrics will depend on your registry implementation.
If I take prometheus, you can easily expose the JVM metrics using the [included-collectors](https://github.com/prometheus/client_java/blob/40e6eec96f4b68870e8bf18ccecf3019355e6bdb/README.md#included-collectors) from the java library.

**TLDR**: add `"io.prometheus" % "simpleclient_hotspot" % "0.9.0"`  to your dependencies and call `DefaultExports.initialize()` when you create the `PrometheusRegistry`.

You'll get all the metrics you want in the registry:

```
# TYPE jvm_classes_loaded gauge
# TYPE jvm_classes_loaded_total counter
# TYPE jvm_classes_unloaded_total counter
# TYPE jvm_memory_pool_allocated_bytes_total counter
# TYPE jvm_buffer_pool_used_bytes gauge
# TYPE jvm_buffer_pool_capacity_bytes gauge
# TYPE jvm_buffer_pool_used_buffers gauge
# TYPE jvm_memory_bytes_used gauge
# TYPE jvm_memory_bytes_committed gauge
# TYPE jvm_memory_bytes_max gauge
# TYPE jvm_memory_bytes_init gauge
# TYPE jvm_memory_pool_bytes_used gauge
# TYPE jvm_memory_pool_bytes_committed gauge
# TYPE jvm_memory_pool_bytes_max gauge
# TYPE jvm_memory_pool_bytes_init gauge
# TYPE jvm_info gauge
# TYPE jvm_threads_current gauge
# TYPE jvm_threads_daemon gauge
# TYPE jvm_threads_peak gauge
# TYPE jvm_threads_started_total counter
# TYPE jvm_threads_deadlocked gauge
# TYPE jvm_threads_deadlocked_monitor gauge
# TYPE jvm_threads_state gauge
# TYPE jvm_gc_collection_seconds summar
```

I'll add that to the README since this is an interesting use case :)

**Comment by RustedBones** [comment]
@rparree Did that help ?

**Comment by rparree** [comment]
@RustedBones sorry for the late reply. Yes it works. I only just got to it. 

tx.
